import React from 'react'
import styles from '../../Companents/Condition/Condition.module.scss'
const Condition = () => {
  return (
    <div className={styles.condition}>
       <div className={styles.container}>
      <h2>DAŞINMA ŞƏRTLƏRİ</h2>
      <p>Bildirmək istərdik ki, Azərbaycan Respublikası Nazirlər Kabinetinin  <span>  305 saylı qərarında edilmiş yeni dəyişikliklərə əsasən</span>  Sifarişçi daşıyıcı şirkət vasitəsilə öz adına hər təqvim ayı üzrə ümumi  gömrük dəyəri 300 ABŞ dolları ekvivalenti məbləğindən artıq olmayan mallar güzəştli qaydada, yəni gömrük ödənişlərini ödəmədən gömrük sərhədindən keçirilə bilər. Sifarişin dəyəri və daşınma haqqının birlikdə dəyəri hər təqvim ayı üzrə 300 ABŞ dolları məbləğindən artıq olarsa, Sifarişçinin qanunvericiliyə uyğun olaraq sifarişin ümumi dəyərinin maksimum həddi 36% qədər olmaqla gömrük rüsumu ödəmək öhdəliyi yaranacaqdır.Bağlamanızı təhvil almaq üçün ilk öncə ofisimizə yaxınlaşıb, bağlamalarınız üçün daşınma haqqını ödeyib,qaimə və barkodu əldə edirsiniz.Daha sonra bu sənədlər əsasında Hava Nəqliyyatında Baş Gömrük idarəsinə müraciət edərək bağlamanız haqda ətrafrlı məlumat əldə edib,resmiləşdirə  Bakı Kargo terminalıpnda saxlama xerclərini ödəyərək təhvil ala bilərsiniz.Əlavə olaraq aşağıda qeyd edilmiş məhsullar Azərbaycan Respublikasına fiziki şəxslər tərəfindən gətirilməsi və beynəlxalq poçt göndərişləri vasitəsilə alınması qadağan olunmuşdur: -Yivli odlu silah növləri, döyüş sursatı (ov silahları üçün sursatlar istisna edilməklə), hərbi təyinatlı bütün əşyalar, partlayıcı maddələr, hərbi texnika. - Telefonlar,tərkibində batareya olan avadanlıqlar, powerbank-lar - Qida məhsulları - Toz halında məhsullar - Tozsoran - Spirtli içkilərin bütün növləri və tütün məhsulları - Partlayıcı, tezalışan və digər təhlükəli maddələr, eləcə də radioaktiv maddələr ( parfumeriya, sprey, quru şampun, boyalar və s.) - Tibbi məhsullar - Gizli kamera - Akumlyatorlar - Amortizatorlar - Hover Board skuteri - Hava nəqliyyatı ilə daşınılması qadağan olunan əşyalar - Radioaktiv maddələr. - Narkotik və psixotrop maddələr, onlardan istifadə üçün ləvazimat. - Əxlaq pozğunluğunu, zorakılığı, terrorizmi təbliğ və reklam edən materiallar. - Narkotik, psixotrop, zəhərləyici, partlayıcı maddələrin hazırlanması texnologiyasına aid materiallar. - Canlı heyvanlar - Bitki və toxumlar - Hər cür silah növləri, döyüş sursatı, hərbi təyinatlı hər cür əşyalar, partlayıcı maddələr, hərbi texnika. - Xüsusi məxfi rabitə vasitələri, onların şifrləri və istismarı haqqında ədəbiyyat. - Müdafiə, Milli Təhlükəsizlik və Daxili İşlər nazirliklərinin operativ istintaq fəaliyyəti üzrə informasiya sistemləri, sənədləri və arxivləri. - Dövlət əhəmiyyətli sənədlər, ixtiralar, layihələr. - Xammal şəklində olan qiymətli metallar və qiymətli qaşlar. - Dini və Siyasi kitablar -Qanunvericiliyin tələbini ödəməyən digər məhsullar. <br />
Müştərilərimiz saytımızda qeydiyyatdan keçərkən daxil etmiş olduğu bütün şəxsi məlumatlar (ad, soyad, ünvan, telefon, Ş.V nömrəsi, fin kod və s.) başqa üzvlər tərəfindən görülmür və üçüncü şəxslərlə paylaşılmır. Müştəri məlumatları yalnız qanun çərçivəsində nəzərdə tutulan orqanlara bildirilə bilər. <br />
Sifariş əsasında Sifarişçi razılığı olmadan açılmasına icazə verilməyən daşınan bağlamadakı əşyanın qüsurlu və əksik olmasına görə “Daşıyıcı” heç bir məsuliyyət daşımır.Türkiyə anbarına təhvil verilmiş bağlamalar 15 günə kimi sistemə qəbul edilə bilər. (Nəzərə alınki,Endirim günlərində biraz daha uzana bilər) Sistemə qəbul edilmiş bağlamalar ən gec 1 həftə ərzində Bakıya yola salınır. 
Sifarişlər Daşıyıcı tərəfindən sığortalanmır və Daşıyıcı buna görə heç bir məsuliyyət daşımır. Qırılabilən məhsullar mağaza tərəfindən daşınma standartlarına uyğun paketlənərsə, bağlamanın üzərində “Qırıla bilən məhsul” olması ilə bağlı etiket varsa və bağlamalarda hər hansı zədələnmə halı olarsa, müştərinin ödədiyi məbləğ şirkətimiz tərəfindən kompensasiya edilir. Qəbul olunan bağlama ofisimizdə, kuryer çatdırılması edilibsə kuryerin yanında yoxlanılmalıdır. Məhsulda hər hansı bir xəsarət olduğu təqdirdə yerindəcə əməkdaşlarımıza və ya kuryerə məlumat təqdim edilməlidir. Əks təqdirdə sonradan aşkarlanmış hər hansı bir çatışmazlığa görə daşıyıcı məsuliyyət daşımır. <br />
Sifariş edilmiş bağlama “Daşıyıcı”nın anbarına daxil olduqdan sonra “Daşıyıcı” tərəfindən Sifarişçiyə bu barədə zəng, sms və ya email vasitəsilə məlumat  veriləcək. Bundan sonra Sifarişçi “Daşıyıcı” tərəfindən rəsmi qaydada məlumatlandırılmış hesab ediləcək.  Türkiyə ofisinə çatan bağlamalar 5 gün ərzində bəyan edilməzsə hər bir  bağlama üçün  “Daşıyıcı” cərimə tətbiq edə bilər.  Bəyan edilmiş bağlamalar 3-6 iş günü ərzində Sifarişçi  seçdiyi  ofisindən götürə biləcək. Qeyd etmək lazımdır ki, bölgə məntəqələrimizə bağlamalar daşınma haqqını ödədikdən sonra 3-10 iş günü ərzində bölgə məntəqəsində olur.Əgər Sifarişçi bağlamanın birbaşa ünvanına çatdırılmasını istəyərsə, bu zaman www.kango.az səhifəsindən ödənişli kuryer xidmətini seçə bilər. <br />
Sifariş olunan bağlamanın ofisdən təhvil alınması barədə “Daşıyıcı” tərəfindən Sifarişçiyə bu barədə məlumat verildiyi andan etibarən, bağlama 15 (on beş) gün ərzində Sifarişçi tərəfindən təhvil alınmadığı təqdirdə, növbəti 15 (on beş) gün ərzində hər gün üçün 1 manat anbar xidməti haqqı hesablanır. Sifarişçi “Daşıyıcı”  qarşısında bütün maddi öhdəliklərini ödəyənədək bağlamanı təhvil ala bilməz. 1 ay sonra Sifarişçi bağlamanı ister Azərbaycan istər Türkiyə anbarlarından təhvil almadığı təqdirdə bağlamadakı əmlak “Daşıyıcı”nın mülkiyyətinə keçir. Müştəri sorğusu mehsul daşıyıcı şirkətə daxil olduqdan 1 ay müddetində araşdırıla bilər.1 ay bitdikdən sonra  daxil olan sorğular əsasızdır və daşıyıcı şirkət məsuliyyət daşımır. <br />
Müştərilər AZN balansını geri almaq istədikləri zaman 2.5% komisiya, TL balanslarını geri almaq istədikləri zaman 5% komisiya tutularaq yerdə qalan məbləğ bank kartlarına veya nəğd geri qaytarılır. Geri qaytarılan ödənişlər 14-21 iş gün içində müştərinin bank hesabında görsənir. <br />
Sifariş edilmiş bağlamanın “Daşıyıcı”dan asılı olmayan səbəblərə görə gecikməsi hallarında və ya satıcı bağlamanı daşıyıcı şirkətə çatdırmadığı halda (Satıcı mağaza, Avia reyslər, Gömrük nəzarət yoxlamaları və s bu kimi gecikmələr) “Daşıyıcı” heç bir məsuliyyət daşımır və sifarişdən imtina halı kimi dəyərləndirilə bilməz. Əlavə olaraq bildirmək istərdik ki, bu cür şikayətlər “Daşıyıcı” ilə Sifarişçi arasında hər hansı bir mübahisə predmeti ola bilməz.Xarici anbara daxil olan bağlama 15 iş gününə qədər gecikə bilər <br />
Sifarişçi ilə aparılan bütün məlumat mübadiləsi, habelə Sifarişçiyə aid şəxsi məlumatların hər biri “Daşıyıcı” tərərfindən arxivləşdirilir və konfidensiallıq “Kango” MMC tərəfindən qorunur. <br />
Çatdırılma ödənişləri hər bir bağlama üçün ayrılıqda hesablanır <br />
Türkiyədən iadə xidməti zamanı müştəri info@kango.az email adresinə iadə ediləcək Türkiyə daxili kargonun adını və iadə kodunu bildirməlidir. Bu məlumatlar təqdim edildikdən 72 saat sonra bağlama Türkiyə anbarından iadə edilir. (Bəzi hallarda bu proses 7 iş günü də ola bilir) Qeyd edək ki, PTT kargo ilə iadə zamanı iadə kodu PTT kargonun sistemində çox zaman tanınmadığı üçün yenidən kod alınmalıdır. Bu zaman müştəriyə bununla bağlı məlumat “Daşıyıcı” tərəfindən verilir. Bağlama müştərinin qeyd etdiyi daxili kargo şirkətinə təhvil verildikdən sonrakı proseslər “Daşıyıcı”-nın məsuliyyətində deyildir və iadənin vəya ödənişin satıcı tərəfdən qəbul edilməməsi zamanı “Daşıyıcı” məsuliyyət daşımır.</p>
      </div>
    </div>
  )
}

export default Condition
